# MongoDB Configuration
spring.mongodb.uri=mongodb://localhost:27017/subscriptiondb

# JWT Configuration
jwt.secret=your_secret_key
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aishwaryabh18@gmail.com
spring.mail.password=your_app_password

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server Configuration
server.port=8080